### ISSUE TITLE
Strange behaviour of padding

### ISSUE THREAD

**Issue by Burtan** [h6ah4i/android-verticalseekbar#3]
Hi,
padding works very strange when used on VerticalSeekBar (not the wrapper). Padding(all) seems to work for left and right but not top and bottom. PaddingLeft/Right seems to work for bottom only. Also padding works differently between API23 and previous APIs, at least inside of CardViews.
Best,
Burtan

**Comment by h6ah4i** [comment]
Hi, @Burtan. Thank you for the issue report. I hope I have fixed this issue by [this commit](https://github.com/h6ah4i/android-verticalseekbar/commit/2c901c59b230d1f94abdbe24165972bf72454b80).

Could you try the latest develop branch code and check whether it works as expected on your app? Thanks.

``` gradle
repositories {
    maven { url "https://jitpack.io" }
}

dependencies {
 compile 'com.github.h6ah4i:android-verticalseekbar:2c901c59b230d1f94abdbe24165972bf72454b80'
}
```

**Comment by Burtan** [comment]
Is the dependencies link correct? I cannot resolve it, although jitpack is added to the repo list.

**Comment by h6ah4i** [comment]
At least the above gradle settings code works for me.

**Comment by h6ah4i** [comment]
@Burtan Hi. Any updates on this issue?

**Comment by Burtan** [comment]
Hi, the gradle compile link still does not work for me. I've tried to download the source code and import it as a module into my project, but the module had missing files and thus didn't work.

**Comment by h6ah4i** [comment]
@Burtan Hmm... that seems strange. JitPack is working well, and the repository contains full of required files.

Could you upload the error log messages here? I will take a look at it.

**Comment by h6ah4i** [comment]
@Burtan Hi. Any progress? I am going to merge the develop branch and release it as v0.7.0 on this weekend .

**Comment by h6ah4i** [comment]
NOTE: 
Padding `android:paddingLeft` and `android:paddingRight` are just ignored for `SeekBar` on Android 5.0 or later, so `VerticalSeekBar` also affects the same limitation. The commit 2c901c59b230d1f94abdbe24165972bf72454b80 fixes broken padding handling on API level 10 and improves touch event handling with padding specified `VerticalSeekBar`.

**Comment by h6ah4i** [comment]
v0.7.0 is out.

**Comment by Burtan** [comment]
I was finally able to test it and it works great, thanks!
